spring:
  profiles:
     active: dev
  redis:
    host: localhost
    port: 6379
    #password: 990825
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 100000ms
  mail:
    host: smtp.qq.com
    port: 587
    username: 511928849@qq.com
    password: oxoqbjeauangbhhg
    default-encoding: UTF-8
    smtp:
      socketFactoryClass: javax.net.ssl.SSLSocketFactory
    debug: true


myEmail: 511928849@qq.com

#七牛云配置信息
qiniu:
  accessKey: xrPEmua656LEeVpX4JEg3ZEA8r8-v5vMZdIItS1H
  secretKey: gV71mZurQA3Y9qUD6aY2fanEYMw_IOeXS4XHSNhf
  bucketName: code-b-image
  fileDomain: img.xuhaobo.site


