spring:
#  thymeleaf:
#    mode: HTML
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

#七牛云配置信息
qiniu:
  accessKey: *
  secretKey: *
  bucketName: *
  fileDomain: *



