spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xhb_blog?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: admin
    initSQL: set names utf8mb4
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 600000
      maximum-pool-size: 500      #更改最大连接数为500
      max-lifetime: 1800000
      minimum-idle: 20
      validation-timeout: 3000
      idle-timeout: 60000
      connection-init-sql: SET NAMES utf8mb4
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    favicon:
      enabled=false:
  aop:
    auto: true


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



server:
  servlet:
    session:
      timeout: 7200
  port: 80
  max-http-header-size: 1024000